const inventory = [
	{
		"product_id": 1,
		"product_name": "Inuyasha",
		"franchise_sort": 81,
		"img_name": "inuyasha.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Inuyasha",
		"characters": "Inuyasha",
		"product_includes": "- Inuyasha\n- Tessaiga accessory",
		"has_accessory": "TRUE"
	},
	{
		"product_id": 2,
		"product_name": "Goku",
		"franchise_sort": 51,
		"img_name": "goku.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Dragonball Z",
		"characters": "Goku",
		"product_includes": "- Goku",
		"has_accessory": ""
	},
	{
		"product_id": 3,
		"product_name": "Haruhi Suzumiya",
		"franchise_sort": 72,
		"img_name": "haruhi.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Haruhi Suzumiya",
		"characters": "Haruhi Suzymiya",
		"product_includes": "- Haruhi Suzymiya",
		"has_accessory": ""
	},
	{
		"product_id": 4,
		"product_name": "Hikaru Shindou",
		"franchise_sort": 74,
		"img_name": "hikaru.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Hikaru no Go",
		"characters": "Hikaru Shindou",
		"product_includes": "- Hikaru Shindou",
		"has_accessory": ""
	},
	{
		"product_id": 8,
		"product_name": "Naruto",
		"franchise_sort": 116,
		"img_name": "naruto.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Naruto",
		"characters": "Naruto",
		"product_includes": "- Naruto",
		"has_accessory": ""
	},
	{
		"product_id": 9,
		"product_name": "Darth Vader",
		"franchise_sort": 165,
		"img_name": "vader.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Star Wars",
		"characters": "Darth Vader",
		"product_includes": "- Darth Vader",
		"has_accessory": ""
	},
	{
		"product_id": 10,
		"product_name": "Sonic",
		"franchise_sort": 160,
		"img_name": "sonic.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Sonic",
		"characters": "Sonic",
		"product_includes": "- Sonic",
		"has_accessory": ""
	},
	{
		"product_id": 11,
		"product_name": "Hinata",
		"franchise_sort": 115,
		"img_name": "hinata.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": -1,
		"price": "$3",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Naruto",
		"characters": "Hinata",
		"product_includes": "- Hinata",
		"has_accessory": ""
	},
	{
		"product_id": 12,
		"product_name": "Yugi",
		"franchise_sort": 182,
		"img_name": "yugi.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Yu-Gi-Oh!",
		"characters": "Yugi",
		"product_includes": "- Yugi",
		"has_accessory": ""
	},
	{
		"product_id": 13,
		"product_name": "One Piece Set",
		"franchise_sort": 119,
		"img_name": "onepiece.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "One Piece",
		"characters": "Luffy, Nami, Zoro",
		"product_includes": "- Luffy\n- Nami\n- Zoro",
		"has_accessory": ""
	},
	{
		"product_id": 14,
		"product_name": "Sailor Moon",
		"franchise_sort": 156,
		"img_name": "sailormoon.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Sailor Moon",
		"characters": "Sailor Moon",
		"product_includes": "- Sailor Moon",
		"has_accessory": ""
	},
	{
		"product_id": 15,
		"product_name": "Zelda Set 1",
		"franchise_sort": 188,
		"img_name": "zelda1.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Zelda: Twilight Princess",
		"characters": "Link, Midna",
		"product_includes": "- Link\n- Midna\n- Hylian Shield accessory",
		"has_accessory": "TRUE"
	},
	{
		"product_id": 16,
		"product_name": "Fullmetal Alchemist Set 1",
		"franchise_sort": 65,
		"img_name": "fma1.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Fullmetal Alchemist",
		"characters": "Edward, Alphonse, Winry",
		"product_includes": "- Edward\n- Alphonse\n- Winry",
		"has_accessory": ""
	},
	{
		"product_id": 17,
		"product_name": "Death Note Set",
		"franchise_sort": 29,
		"img_name": "deathnote.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Death Note",
		"characters": "Light, L, Misa",
		"product_includes": "- Light\n- L\n- Misa\n- Death Note accessory\n- mochi dango accessory",
		"has_accessory": "TRUE"
	},
	{
		"product_id": 18,
		"product_name": "Cloud",
		"franchise_sort": 57,
		"img_name": "cloud.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Final Fantasy (VII)",
		"characters": "Cloud",
		"product_includes": "- Cloud\n- buster sword accessory",
		"has_accessory": "TRUE"
	},
	{
		"product_id": 19,
		"product_name": "Avatar Set 1",
		"franchise_sort": 10,
		"img_name": "avatar1.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "Avatar: The Last Airbender",
		"characters": "Aang, Katara, Sokka",
		"product_includes": "- Aang\n- Katara\n- Sokka",
		"has_accessory": ""
	},
	{
		"product_id": 20,
		"product_name": "Metroid Set",
		"franchise_sort": 100,
		"img_name": "metroid.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Metroid",
		"characters": "Samus, Zero Suit Samus",
		"product_includes": "- Samus\n- Zero Suit Samus",
		"has_accessory": ""
	},
	{
		"product_id": 21,
		"product_name": "Tenth Doctor",
		"franchise_sort": 41,
		"img_name": "doc10.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Doctor Who",
		"characters": "Tenth Doctor",
		"product_includes": "- Tenth Doctor\n- 3-D glasses accessory",
		"has_accessory": "TRUE"
	},
	{
		"product_id": 22,
		"product_name": "Dr. Horrible Set",
		"franchise_sort": 47,
		"img_name": "drhorrible.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Dr. Horrible",
		"characters": "Cpt Hammer, Dr. Horrible",
		"product_includes": "- Captain Hammer\n- Dr. Horrible",
		"has_accessory": ""
	},
	{
		"product_id": 23,
		"product_name": "Sasuke",
		"franchise_sort": 117,
		"img_name": "sasuke.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Naruto",
		"characters": "Sasuke",
		"product_includes": "- Sasuke",
		"has_accessory": ""
	},
	{
		"product_id": 24,
		"product_name": "Roxas",
		"franchise_sort": 88,
		"img_name": "roxas.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Kingdom Hearts",
		"characters": "Roxas",
		"product_includes": "- Roxas",
		"has_accessory": ""
	},
	{
		"product_id": 25,
		"product_name": "Sora",
		"franchise_sort": 89,
		"img_name": "sora.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Kingdom Hearts",
		"characters": "Sora",
		"product_includes": "- Sora\n- keyblade accessory",
		"has_accessory": "TRUE"
	},
	{
		"product_id": 26,
		"product_name": "Eleventh Doctor",
		"franchise_sort": 42,
		"img_name": "doc11.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Doctor Who",
		"characters": "Eleventh Doctor",
		"product_includes": "- Eleventh Doctor\n- fez accessory",
		"has_accessory": "TRUE"
	},
	{
		"product_id": 27,
		"product_name": "Miku Hatsune",
		"franchise_sort": 178,
		"img_name": "miku.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 6,
		"category_name": "Miscellaneous",
		"franchise": "Vocaloid",
		"characters": "Miku Hatsune",
		"product_includes": "- Miku Hatsune\n- leek accessory",
		"has_accessory": "TRUE"
	},
	{
		"product_id": 28,
		"product_name": "Sweeney Todd",
		"franchise_sort": 170,
		"img_name": "sweeney.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Sweeney Todd",
		"characters": "Sweeney Todd",
		"product_includes": "- Sweeney Todd",
		"has_accessory": ""
	},
	{
		"product_id": 29,
		"product_name": "Fullmetal Alchemist Set 2",
		"franchise_sort": 66,
		"img_name": "fma2.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Fullmetal Alchemist",
		"characters": "Armstrong, Maes Hughes",
		"product_includes": "- Armstrong\n- Maes Hughes",
		"has_accessory": ""
	},
	{
		"product_id": 30,
		"product_name": "Konata Izumi",
		"franchise_sort": 92,
		"img_name": "konata.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Lucky Star",
		"characters": "Konata Izumi",
		"product_includes": "- Konata Izumi",
		"has_accessory": ""
	},
	{
		"product_id": 31,
		"product_name": "Toothless",
		"franchise_sort": 76,
		"img_name": "toothless.png",
		"big_character_count": "",
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 0.5,
		"price_adjust": "",
		"price": "$2",
		"total_character_count": 1,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "How to Train Your Dragon",
		"characters": "Toothless",
		"product_includes": "- Toothless",
		"has_accessory": ""
	},
	{
		"product_id": 32,
		"product_name": "Disgaea Set 1",
		"franchise_sort": 30,
		"img_name": "disgaea1.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Disgaea",
		"characters": "Laharl, Flonne",
		"product_includes": "- Laharl\n- Flonne",
		"has_accessory": ""
	},
	{
		"product_id": 33,
		"product_name": "Disgaea Set 2",
		"franchise_sort": 31,
		"img_name": "disgaea2.png",
		"big_character_count": 1,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 2,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Disgaea",
		"characters": "Etna, Prinny",
		"product_includes": "- Etna\n- Prinny",
		"has_accessory": ""
	},
	{
		"product_id": 35,
		"product_name": "Captain Jack Harkness",
		"franchise_sort": 175,
		"img_name": "captainjack.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Torchwood",
		"characters": "Captain Jack Harkness",
		"product_includes": "- Captain Jack Harkness",
		"has_accessory": ""
	},
	{
		"product_id": 36,
		"product_name": "Cowboy Bebop Set 2",
		"franchise_sort": 26,
		"img_name": "cowboybebop2.png",
		"big_character_count": 1,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Cowboy Bebop",
		"characters": "Ed, Ein",
		"product_includes": "- Ed\n- Ein\n- goggles accessory",
		"has_accessory": "TRUE"
	},
	{
		"product_id": 37,
		"product_name": "Pokémon Starters 1",
		"franchise_sort": 137,
		"img_name": "starter1.png",
		"big_character_count": "",
		"mini_character_count": 3,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 3,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Bulbasaur, Squirtle, Charmander",
		"product_includes": "- Bulbasaur\n- Squirtle\n- Charmander",
		"has_accessory": ""
	},
	{
		"product_id": 38,
		"product_name": "Pokémon Starters 2",
		"franchise_sort": 138,
		"img_name": "starter2.png",
		"big_character_count": "",
		"mini_character_count": 3,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 3,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Chikorita, Cyndaquil, Totodile",
		"product_includes": "- Chikorita\n- Cyndaquil\n- Totodile",
		"has_accessory": ""
	},
	{
		"product_id": 39,
		"product_name": "Pokémon Starters 3",
		"franchise_sort": 139,
		"img_name": "starter3.png",
		"big_character_count": "",
		"mini_character_count": 3,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 3,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Treecko, Torchic, Mudkip",
		"product_includes": "- Treecko\n- Torchic\n- Mudkip",
		"has_accessory": ""
	},
	{
		"product_id": 40,
		"product_name": "Pokémon Starters 4",
		"franchise_sort": 140,
		"img_name": "starter4.png",
		"big_character_count": "",
		"mini_character_count": 3,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 3,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Turtwig, Chimchar, Piplup",
		"product_includes": "- Turtwig\n- Chimchar\n- Piplup",
		"has_accessory": ""
	},
	{
		"product_id": 41,
		"product_name": "Pokémon Starters 5",
		"franchise_sort": 141,
		"img_name": "starter5.png",
		"big_character_count": "",
		"mini_character_count": 3,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 3,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Snivy, Tepig, Oshawott",
		"product_includes": "- Snivy\n- Tepig\n- Oshawott",
		"has_accessory": ""
	},
	{
		"product_id": 42,
		"product_name": "Nausicaä Set",
		"franchise_sort": 118,
		"img_name": "nausicaa.png",
		"big_character_count": 1,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Nausicaa",
		"characters": "Nausicaä, Teto",
		"product_includes": "- Nausicaä\n- Teto",
		"has_accessory": ""
	},
	{
		"product_id": 43,
		"product_name": "Solid Snake",
		"franchise_sort": 98,
		"img_name": "snake.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Metal Gear Solid",
		"characters": "Solid Snake",
		"product_includes": "- Solid Snake",
		"has_accessory": ""
	},
	{
		"product_id": 44,
		"product_name": "Bleach Set",
		"franchise_sort": 18,
		"img_name": "bleach.png",
		"big_character_count": 2,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 2.5,
		"price_adjust": "",
		"price": "$10",
		"total_character_count": 3,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Bleach",
		"characters": "Ichigo, Rukia, Kon",
		"product_includes": "- Ichigo\n- Rukia\n- Kon\n- Zangetsu accessory",
		"has_accessory": "TRUE"
	},
	{
		"product_id": 45,
		"product_name": "Eeveelutions Set 1",
		"franchise_sort": 126,
		"img_name": "eeveelutions1.png",
		"big_character_count": "",
		"mini_character_count": 4,
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": 1,
		"price": "$9",
		"total_character_count": 4,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Eevee, Vaporeon, Jolteon, Flareon",
		"product_includes": "- Eevee\n- Vaporeon\n- Jolteon\n- Flareon",
		"has_accessory": ""
	},
	{
		"product_id": 46,
		"product_name": "Eeveelutions Set 2",
		"franchise_sort": 127,
		"img_name": "eeveelutions2.png",
		"big_character_count": "",
		"mini_character_count": 4,
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": 1,
		"price": "$9",
		"total_character_count": 4,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Espeon, Umbreon, Leafeon, Glaceon",
		"product_includes": "- Espeon\n- Umbreon\n- Leafeon\n- Glaceon",
		"has_accessory": ""
	},
	{
		"product_id": 47,
		"product_name": "Trainer Misty Set",
		"franchise_sort": 146,
		"img_name": "misty.png",
		"big_character_count": 1,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 2,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Misty, Psyduck",
		"product_includes": "- Misty\n- Psyduck",
		"has_accessory": ""
	},
	{
		"product_id": 48,
		"product_name": "Trainer Ash Set",
		"franchise_sort": 144,
		"img_name": "ash.png",
		"big_character_count": 1,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 2,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Ash, Pikachu",
		"product_includes": "- Ash\n- Pikachu",
		"has_accessory": ""
	},
	{
		"product_id": 49,
		"product_name": "Princess Mononoke Set",
		"franchise_sort": 149,
		"img_name": "mononoke.png",
		"big_character_count": 2,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 2.5,
		"price_adjust": "",
		"price": "$10",
		"total_character_count": 3,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Princess Mononoke",
		"characters": "Ashitaka, San, Kodama",
		"product_includes": "- Ashitaka\n- San\n- Kodama",
		"has_accessory": ""
	},
	{
		"product_id": 50,
		"product_name": "Trainer Brock Set",
		"franchise_sort": 145,
		"img_name": "brock.png",
		"big_character_count": 1,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 2,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Brock, Vulpix",
		"product_includes": "- Brock\n- Vulpix\n- heart-eyes accessory",
		"has_accessory": "TRUE"
	},
	{
		"product_id": 51,
		"product_name": "Cowboy Bebop Set 1",
		"franchise_sort": 25,
		"img_name": "cowboybebop1.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Cowboy Bebop",
		"characters": "Spike, Jet, Faye",
		"product_includes": "- Spike\n- Jet\n- Faye",
		"has_accessory": ""
	},
	{
		"product_id": 52,
		"product_name": "Katamari Prince",
		"franchise_sort": 86,
		"img_name": "katamari.png",
		"big_character_count": "",
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 0.5,
		"price_adjust": "",
		"price": "$2",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Katamari",
		"characters": "The Prince",
		"product_includes": "- The Prince",
		"has_accessory": ""
	},
	{
		"product_id": 53,
		"product_name": "Legendaries Gen I Set",
		"franchise_sort": 133,
		"img_name": "legendary.png",
		"big_character_count": "",
		"mini_character_count": 2,
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": 1,
		"price": "$5",
		"total_character_count": 2,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Mew, Mewtwo",
		"product_includes": "- Mew\n- Mewtwo",
		"has_accessory": ""
	},
	{
		"product_id": 54,
		"product_name": "Avatar Set 2",
		"franchise_sort": 11,
		"img_name": "avatar2.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "Avatar: The Last Airbender",
		"characters": "Zuko, Iroh, Toph",
		"product_includes": "- Zuko\n- Iroh\n- Toph",
		"has_accessory": ""
	},
	{
		"product_id": 55,
		"product_name": "Spirited Away Set 1",
		"franchise_sort": 161,
		"img_name": "spirited1.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Spirited Away",
		"characters": "Chihiro, Haku",
		"product_includes": "- Chihiro\n- Haku",
		"has_accessory": ""
	},
	{
		"product_id": 56,
		"product_name": "Spirited Away Set 2",
		"franchise_sort": 162,
		"img_name": "spirited2.png",
		"big_character_count": 1,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Spirited Away",
		"characters": "No-Face, Mouse with Bird",
		"product_includes": "- No-Face\n- Mouse with Bird",
		"has_accessory": ""
	},
	{
		"product_id": 57,
		"product_name": "Sack Person",
		"franchise_sort": 91,
		"img_name": "sackboy.png",
		"big_character_count": "",
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 0.5,
		"price_adjust": "",
		"price": "$2",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Little Big Planet",
		"characters": "Sack Boy",
		"product_includes": "- Sack Boy",
		"has_accessory": ""
	},
	{
		"product_id": 59,
		"product_name": "Escaflowne Boys Set",
		"franchise_sort": 52,
		"img_name": "escaboys.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Escaflowne",
		"characters": "Van, Allen",
		"product_includes": "- Van\n- Allen",
		"has_accessory": ""
	},
	{
		"product_id": 60,
		"product_name": "Ranma Set 1",
		"franchise_sort": 150,
		"img_name": "ranma1.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Ranma 1/2",
		"characters": "Ranma, Ranko",
		"product_includes": "- Ranma\n- Ranko",
		"has_accessory": ""
	},
	{
		"product_id": 61,
		"product_name": "Belldandy",
		"franchise_sort": 1,
		"img_name": "belldandy.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": 0.5,
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Ah! My Goddess",
		"characters": "Belldandy",
		"product_includes": "- Belldandy",
		"has_accessory": ""
	},
	{
		"product_id": 61,
		"product_name": "Cthulhu",
		"franchise_sort": 56,
		"img_name": "cthulhu.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 6,
		"category_name": "Miscellaneous",
		"franchise": "Fandemonium",
		"characters": "Cthulhu",
		"product_includes": "- Cthulhu",
		"has_accessory": ""
	},
	{
		"product_id": 62,
		"product_name": "Fourth Doctor",
		"franchise_sort": 35,
		"img_name": "doc04.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Doctor Who",
		"characters": "Fourth Doctor",
		"product_includes": "- Fourth Doctor",
		"has_accessory": ""
	},
	{
		"product_id": 63,
		"product_name": "Black Butler Set",
		"franchise_sort": 14,
		"img_name": "blackbutler.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Black Butler",
		"characters": "Ciel, Sebastian",
		"product_includes": "- Ciel\n- Sebastian",
		"has_accessory": ""
	},
	{
		"product_id": 65,
		"product_name": "Gir",
		"franchise_sort": 85,
		"img_name": "gir.png",
		"big_character_count": "",
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 0.5,
		"price_adjust": "",
		"price": "$2",
		"total_character_count": 1,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "Invader Zim",
		"characters": "Gir",
		"product_includes": "- Gir",
		"has_accessory": ""
	},
	{
		"product_id": 67,
		"product_name": "Yotsuba",
		"franchise_sort": 180,
		"img_name": "yotsuba.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Yotsuba&!",
		"characters": "Yotsuba",
		"product_includes": "- Yotsuba",
		"has_accessory": ""
	},
	{
		"product_id": 68,
		"product_name": "Rin",
		"franchise_sort": 19,
		"img_name": "rin.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Blue Exorcist",
		"characters": "Rin",
		"product_includes": "- Rin",
		"has_accessory": ""
	},
	{
		"product_id": 69,
		"product_name": "Ninth Doctor",
		"franchise_sort": 40,
		"img_name": "doc09.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Doctor Who",
		"characters": "Ninth Doctor",
		"product_includes": "- Ninth Doctor",
		"has_accessory": ""
	},
	{
		"product_id": 70,
		"product_name": "Yuu Yuu Hakusho Hiei Set",
		"franchise_sort": 183,
		"img_name": "hieis.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Yuu Yuu Hakusho",
		"characters": "Hiei, Demon Hiei",
		"product_includes": "- Hiei\n- Demon Hiei",
		"has_accessory": ""
	},
	{
		"product_id": 71,
		"product_name": "Kenshin",
		"franchise_sort": 155,
		"img_name": "kenshin.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Rurouni Kenshin",
		"characters": "Kenshin",
		"product_includes": "- Kenshin",
		"has_accessory": ""
	},
	{
		"product_id": 72,
		"product_name": "My Little Pony : FiM Set 3",
		"franchise_sort": 106,
		"img_name": "mlp3.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "My Little Pony: Friendship is Magic",
		"characters": "Rainbow Dash, Fluttershy",
		"product_includes": "- Rainbow Dash\n- Fluttershy",
		"has_accessory": ""
	},
	{
		"product_id": 73,
		"product_name": "My Little Pony : FiM Set 2",
		"franchise_sort": 105,
		"img_name": "mlp2.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "My Little Pony: Friendship is Magic",
		"characters": "Applejack, Pinkie Pie",
		"product_includes": "- Applejack\n- Pinkie Pie",
		"has_accessory": ""
	},
	{
		"product_id": 74,
		"product_name": "My Little Pony : FiM Set 1",
		"franchise_sort": 104,
		"img_name": "mlp1.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "My Little Pony: Friendship is Magic",
		"characters": "Twilight Sparkle, Rarity",
		"product_includes": "- Twilight Sparkle\n- Rarity",
		"has_accessory": ""
	},
	{
		"product_id": 75,
		"product_name": "Fullmetal Alchemist Set 3",
		"franchise_sort": 67,
		"img_name": "fma3.png",
		"big_character_count": 2,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 2.5,
		"price_adjust": "",
		"price": "$10",
		"total_character_count": 3,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Fullmetal Alchemist",
		"characters": "Mustang, Hawkeye, Black Hayate",
		"product_includes": "- Mustang\n- Hawkeye\n- Black Hayate",
		"has_accessory": ""
	},
	{
		"product_id": 76,
		"product_name": "Ponyo",
		"franchise_sort": 147,
		"img_name": "ponyo.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Ponyo",
		"characters": "Ponyo",
		"product_includes": "- Ponyo",
		"has_accessory": ""
	},
	{
		"product_id": 77,
		"product_name": "Dragonball Z Set 2",
		"franchise_sort": 50,
		"img_name": "dbz2.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Dragonball Z",
		"characters": "Vegeta, Nappa",
		"product_includes": "- Vegeta\n- Nappa",
		"has_accessory": ""
	},
	{
		"product_id": 78,
		"product_name": "Dragonball Z Set 1",
		"franchise_sort": 49,
		"img_name": "dbz1.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Dragonball Z",
		"characters": "Goku, Piccolo",
		"product_includes": "- Goku\n- Piccolo",
		"has_accessory": ""
	},
	{
		"product_id": 79,
		"product_name": "Avatar Set 3",
		"franchise_sort": 12,
		"img_name": "avatar3.png",
		"big_character_count": 1,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 2,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "Avatar: The Last Airbender",
		"characters": "Momo, Appa",
		"product_includes": "- Momo\n- Appa",
		"has_accessory": ""
	},
	{
		"product_id": 80,
		"product_name": "Yuu Yuu Hakusho Kurama Set",
		"franchise_sort": 184,
		"img_name": "kuramas.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Yuu Yuu Hakusho",
		"characters": "Kurama, Demon Kurama",
		"product_includes": "- Kurama\n- Demon Kurama",
		"has_accessory": ""
	},
	{
		"product_id": 81,
		"product_name": "Zelda Set 2",
		"franchise_sort": 185,
		"img_name": "zelda2.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Zelda",
		"characters": "Zelda, Sheik",
		"product_includes": "- Zelda\n- Sheik",
		"has_accessory": ""
	},
	{
		"product_id": 82,
		"product_name": "Ranma Set 2",
		"franchise_sort": 151,
		"img_name": "ranma2.png",
		"big_character_count": 1,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Ranma 1/2",
		"characters": "Ryoga, P-Chan",
		"product_includes": "- Ryoga\n- P-Chan",
		"has_accessory": ""
	},
	{
		"product_id": 83,
		"product_name": "Nyan Cat",
		"franchise_sort": 171,
		"img_name": "nyan.png",
		"big_character_count": "",
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 0.5,
		"price_adjust": "",
		"price": "$2",
		"total_character_count": 1,
		"category_id": 6,
		"category_name": "Miscellaneous",
		"franchise": "the internet",
		"characters": "Nyan Cat",
		"product_includes": "- Nyan Cat",
		"has_accessory": ""
	},
	{
		"product_id": 84,
		"product_name": "Inuyasha Set 1",
		"franchise_sort": 82,
		"img_name": "inuyasha1.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Inuyasha",
		"characters": "Inuyasha, Kagome, Shippo",
		"product_includes": "- Inuyasha\n- Kagome\n- Shippo\n- Tessaiga accessory",
		"has_accessory": "TRUE"
	},
	{
		"product_id": 85,
		"product_name": "Fifth Doctor",
		"franchise_sort": 36,
		"img_name": "doc05.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Doctor Who",
		"characters": "Fifth Doctor",
		"product_includes": "- Fifth Doctor",
		"has_accessory": ""
	},
	{
		"product_id": 86,
		"product_name": "Inuyasha Set 2",
		"franchise_sort": 83,
		"img_name": "inuyasha2.png",
		"big_character_count": 2,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 2.5,
		"price_adjust": "",
		"price": "$10",
		"total_character_count": 3,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Inuyasha",
		"characters": "Miroku, Sango, Kilala",
		"product_includes": "- Miroku\n- Sango\n- Kilala",
		"has_accessory": ""
	},
	{
		"product_id": 87,
		"product_name": "Star Wars Set 1",
		"franchise_sort": 166,
		"img_name": "starwars1.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Star Wars",
		"characters": "Luke, Leia",
		"product_includes": "- Luke\n- Leia",
		"has_accessory": ""
	},
	{
		"product_id": 88,
		"product_name": "Yu-Gi-Oh! Set 1",
		"franchise_sort": 181,
		"img_name": "yugioh1.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Yu-Gi-Oh!",
		"characters": "Yami Yugi, Kaiba",
		"product_includes": "- Yami Yugi\n- Kaiba",
		"has_accessory": ""
	},
	{
		"product_id": 89,
		"product_name": "Inuyasha Set 3",
		"franchise_sort": 84,
		"img_name": "inuyasha3.png",
		"big_character_count": 2,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 2.5,
		"price_adjust": "",
		"price": "$10",
		"total_character_count": 3,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Inuyasha",
		"characters": "Sesshomaru, Jaken, Rin",
		"product_includes": "- Sesshomaru\n- Jaken\n- Rin",
		"has_accessory": ""
	},
	{
		"product_id": 90,
		"product_name": "Gurren Lagann Set",
		"franchise_sort": 70,
		"img_name": "gurrenlagann.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Gurren Lagann",
		"characters": "Simon, Kamina, Yoko",
		"product_includes": "- Simon\n- Kamina\n- Yoko",
		"has_accessory": ""
	},
	{
		"product_id": 91,
		"product_name": "Korra Set 1",
		"franchise_sort": 90,
		"img_name": "korra.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "Legend of Korra",
		"characters": "Korra, Bolin, Mako",
		"product_includes": "- Korra\n- Bolin\n- Mako",
		"has_accessory": ""
	},
	{
		"product_id": 92,
		"product_name": "DW New Companions Set 1",
		"franchise_sort": 45,
		"img_name": "dwnewcompanions.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Doctor Who",
		"characters": "Rose, Martha, Donna",
		"product_includes": "- Rose\n- Martha\n- Donna",
		"has_accessory": ""
	},
	{
		"product_id": 93,
		"product_name": "Mass Effect Set 2",
		"franchise_sort": 97,
		"img_name": "masseffect2.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Mass Effect",
		"characters": "Liara, Tali",
		"product_includes": "- Liara\n- Tali",
		"has_accessory": ""
	},
	{
		"product_id": 94,
		"product_name": "Mass Effect Set 1",
		"franchise_sort": 96,
		"img_name": "masseffect1.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Mass Effect",
		"characters": "Garrus, Wrex",
		"product_includes": "- Garrus\n- Wrex",
		"has_accessory": ""
	},
	{
		"product_id": 95,
		"product_name": "First Doctor",
		"franchise_sort": 32,
		"img_name": "doc01.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Doctor Who",
		"characters": "First Doctor",
		"product_includes": "- First Doctor",
		"has_accessory": ""
	},
	{
		"product_id": 96,
		"product_name": "Skyward Sword Set 2",
		"franchise_sort": 187,
		"img_name": "skywardsword2.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Zelda: Skyward Sword",
		"characters": "Fi, Ghirahim",
		"product_includes": "- Fi\n- Ghirahim",
		"has_accessory": ""
	},
	{
		"product_id": 97,
		"product_name": "Skyward Sword Set 1",
		"franchise_sort": 186,
		"img_name": "skywardsword1.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Zelda: Skyward Sword",
		"characters": "Link, Zelda",
		"product_includes": "- Link\n- Zelda",
		"has_accessory": ""
	},
	{
		"product_id": 98,
		"product_name": "Andalite",
		"franchise_sort": 7,
		"img_name": "andalite.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 6,
		"category_name": "Miscellaneous",
		"franchise": "Animorphs",
		"characters": "Andalite",
		"product_includes": "- Andalite",
		"has_accessory": ""
	},
	{
		"product_id": 100,
		"product_name": "Raiden",
		"franchise_sort": 99,
		"img_name": "raiden.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Metal Gear Solid (2)",
		"characters": "Raiden",
		"product_includes": "- Raiden",
		"has_accessory": ""
	},
	{
		"product_id": 101,
		"product_name": "Second Doctor",
		"franchise_sort": 33,
		"img_name": "doc02.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Doctor Who",
		"characters": "Second Doctor",
		"product_includes": "- Second Doctor",
		"has_accessory": ""
	},
	{
		"product_id": 102,
		"product_name": "Third Doctor",
		"franchise_sort": 34,
		"img_name": "doc03.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Doctor Who",
		"characters": "Third Doctor",
		"product_includes": "- Third Doctor",
		"has_accessory": ""
	},
	{
		"product_id": 103,
		"product_name": "Evangelion Set 2",
		"franchise_sort": 55,
		"img_name": "eva2.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Evangelion",
		"characters": "Asuka, Mari",
		"product_includes": "- Asuka\n- Mari",
		"has_accessory": ""
	},
	{
		"product_id": 104,
		"product_name": "To Love Ru Set 1",
		"franchise_sort": 173,
		"img_name": "toloveru1.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "To Love Ru",
		"characters": "Rito, Lala",
		"product_includes": "- Rito\n- Lala",
		"has_accessory": ""
	},
	{
		"product_id": 105,
		"product_name": "To Love Ru Set 2",
		"franchise_sort": 174,
		"img_name": "toloveru2.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "To Love Ru",
		"characters": "Kotegawa, Tenjouin",
		"product_includes": "- Kotegawa\n- Tenjouin",
		"has_accessory": ""
	},
	{
		"product_id": 106,
		"product_name": "Rosario+Vampire Set",
		"franchise_sort": 154,
		"img_name": "rosario.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Rosario+Vampire",
		"characters": "Tsukune, Moka",
		"product_includes": "- Tsukune\n- Moka",
		"has_accessory": ""
	},
	{
		"product_id": 107,
		"product_name": "Evangelion Set 1",
		"franchise_sort": 54,
		"img_name": "eva1.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Evangelion",
		"characters": "Shinji, Rei",
		"product_includes": "- Shinji\n- Rei",
		"has_accessory": ""
	},
	{
		"product_id": 108,
		"product_name": "Kokoa",
		"franchise_sort": 153,
		"img_name": "kokoa.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Rosario+Vampire",
		"characters": "Kokoa",
		"product_includes": "- Kokoa",
		"has_accessory": ""
	},
	{
		"product_id": 109,
		"product_name": "Gym Leader Elesa Set",
		"franchise_sort": 129,
		"img_name": "elesa.png",
		"big_character_count": 1,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 2,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Elesa, Emolga",
		"product_includes": "- Elesa\n- Emolga",
		"has_accessory": ""
	},
	{
		"product_id": 110,
		"product_name": "Gym Leader Flannery Set",
		"franchise_sort": 130,
		"img_name": "falnnery.png",
		"big_character_count": 1,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 2,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Flannery, Slugma",
		"product_includes": "- Flannery\n- Slugma",
		"has_accessory": ""
	},
	{
		"product_id": 111,
		"product_name": "Pokémon Starters 6",
		"franchise_sort": 142,
		"img_name": "starter6.png",
		"big_character_count": "",
		"mini_character_count": 3,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 3,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Chespin, Fennekin, Froakie",
		"product_includes": "- Chespin\n- Fennekin\n- Froakie",
		"has_accessory": ""
	},
	{
		"product_id": 112,
		"product_name": "Tohru",
		"franchise_sort": 64,
		"img_name": "tohru.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Fruits Basket",
		"characters": "Tohru",
		"product_includes": "- Tohru",
		"has_accessory": ""
	},
	{
		"product_id": 113,
		"product_name": "Fruba Yuki Set",
		"franchise_sort": 63,
		"img_name": "fruba_yuki.png",
		"big_character_count": 1,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Fruits Basket",
		"characters": "Yuki, Mouse-Yuki",
		"product_includes": "- Yuki\n- Mouse-Yuki",
		"has_accessory": ""
	},
	{
		"product_id": 114,
		"product_name": "Fruba Kyo Set",
		"franchise_sort": 62,
		"img_name": "fruba_kyo.png",
		"big_character_count": 1,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Fruits Basket",
		"characters": "Kyo, Cat-Kyo",
		"product_includes": "- Kyo\n- Cat-Kyo",
		"has_accessory": ""
	},
	{
		"product_id": 115,
		"product_name": "Hiccup",
		"franchise_sort": 75,
		"img_name": "hiccup.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "How to Train Your Dragon",
		"characters": "Hiccup",
		"product_includes": "- Hiccup",
		"has_accessory": ""
	},
	{
		"product_id": 116,
		"product_name": "Urd",
		"franchise_sort": 3,
		"img_name": "urd.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": 0.5,
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Ah! My Goddess",
		"characters": "Urd",
		"product_includes": "- Urd",
		"has_accessory": ""
	},
	{
		"product_id": 117,
		"product_name": "Lina Inverse",
		"franchise_sort": 159,
		"img_name": "lina.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Slayers",
		"characters": "Lina Inverse",
		"product_includes": "- Lina Inverse",
		"has_accessory": ""
	},
	{
		"product_id": 118,
		"product_name": "Super Mario Bros. Set 2",
		"franchise_sort": 169,
		"img_name": "mariobros2.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Super Mario Bros.",
		"characters": "Yoshi, Peach",
		"product_includes": "- Yoshi\n- Peach",
		"has_accessory": ""
	},
	{
		"product_id": 119,
		"product_name": "Sherlock Set",
		"franchise_sort": 157,
		"img_name": "sherlock.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Sherlock",
		"characters": "Holmes, Watson",
		"product_includes": "- Holmes\n- Watson",
		"has_accessory": ""
	},
	{
		"product_id": 120,
		"product_name": "My Little Pony : FiM Set 4",
		"franchise_sort": 107,
		"img_name": "mlp4.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "My Little Pony: Friendship is Magic",
		"characters": "Apple Bloom, Scootaloo, Sweetie Belle",
		"product_includes": "- Apple Bloom\n- Scootaloo\n- Sweetie Belle",
		"has_accessory": ""
	},
	{
		"product_id": 121,
		"product_name": "My Little Pony : FiM Set 5",
		"franchise_sort": 108,
		"img_name": "mlp5.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "My Little Pony: Friendship is Magic",
		"characters": "Big Macintosh, Granny Smith",
		"product_includes": "- Big Macintosh\n- Granny Smith",
		"has_accessory": ""
	},
	{
		"product_id": 122,
		"product_name": "My Little Pony : FiM Set 6",
		"franchise_sort": 109,
		"img_name": "mlp6.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "My Little Pony: Friendship is Magic",
		"characters": "Doctor Whooves, Derpy Hooves",
		"product_includes": "- Doctor Whooves\n- Derpy Hooves",
		"has_accessory": ""
	},
	{
		"product_id": 123,
		"product_name": "My Little Pony: FiM Royal Set 2",
		"franchise_sort": 111,
		"img_name": "mlproyal2.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "My Little Pony: Friendship is Magic",
		"characters": "Princess Cadence, Shining Armor",
		"product_includes": "- Princess Cadence\n- Shining Armor",
		"has_accessory": ""
	},
	{
		"product_id": 124,
		"product_name": "My Little Pony: FiM Royal Set 1",
		"franchise_sort": 110,
		"img_name": "mlproyal1.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": 0.5,
		"total_pts": 2.5,
		"price_adjust": -1,
		"price": "$9",
		"total_character_count": 2,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "My Little Pony: Friendship is Magic",
		"characters": "Princess Luna, Princess Celestia",
		"product_includes": "- Princess Luna\n- Princess Celestia",
		"has_accessory": ""
	},
	{
		"product_id": 125,
		"product_name": "Enderman",
		"franchise_sort": 102,
		"img_name": "endermanneo.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Minecraft",
		"characters": "Enderman",
		"product_includes": "- Enderman",
		"has_accessory": ""
	},
	{
		"product_id": 126,
		"product_name": "Creeper",
		"franchise_sort": 101,
		"img_name": "creeperneo.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Minecraft",
		"characters": "Creeper",
		"product_includes": "- Creeper",
		"has_accessory": ""
	},
	{
		"product_id": 127,
		"product_name": "Steve with Tools",
		"franchise_sort": 103,
		"img_name": "steve.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": 0.5,
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Minecraft",
		"characters": "Steve",
		"product_includes": "- Steve\n- diamond pickaxe accessory\n- iron sword accessory\n- stone axe accessory\n- wooden shovel accessory\n- gold hoe accessory",
		"has_accessory": "TRUE"
	},
	{
		"product_id": 128,
		"product_name": "Eighth Doctor",
		"franchise_sort": 39,
		"img_name": "doc08.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Doctor Who",
		"characters": "Eighth Doctor",
		"product_includes": "- Eighth Doctor",
		"has_accessory": ""
	},
	{
		"product_id": 129,
		"product_name": "Seventh Doctor",
		"franchise_sort": 38,
		"img_name": "doc07.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Doctor Who",
		"characters": "Seventh Doctor",
		"product_includes": "- Seventh Doctor",
		"has_accessory": ""
	},
	{
		"product_id": 130,
		"product_name": "Sixth Doctor",
		"franchise_sort": 37,
		"img_name": "doc06.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Doctor Who",
		"characters": "Sixth Doctor",
		"product_includes": "- Sixth Doctor",
		"has_accessory": ""
	},
	{
		"product_id": 131,
		"product_name": "Spike",
		"franchise_sort": 112,
		"img_name": "spike.png",
		"big_character_count": "",
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 0.5,
		"price_adjust": "",
		"price": "$2",
		"total_character_count": 1,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "My Little Pony: Friendship is Magic",
		"characters": "Spike",
		"product_includes": "- Spike",
		"has_accessory": ""
	},
	{
		"product_id": 132,
		"product_name": "Gym Leader Candice Set",
		"franchise_sort": 128,
		"img_name": "candice.png",
		"big_character_count": 1,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 2,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Candice, Sneasel",
		"product_includes": "- Candice\n- Sneasel",
		"has_accessory": ""
	},
	{
		"product_id": 133,
		"product_name": "Gym Leader Whitney Set",
		"franchise_sort": 131,
		"img_name": "whitney.png",
		"big_character_count": 1,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 2,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Whitney, Miltank",
		"product_includes": "- Whitney\n- Miltank",
		"has_accessory": ""
	},
	{
		"product_id": 134,
		"product_name": "Dead or Alive Set",
		"franchise_sort": 28,
		"img_name": "doa.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Dead or Alive",
		"characters": "Ayane, Kasumi",
		"product_includes": "- Ayane\n- Kasumi",
		"has_accessory": ""
	},
	{
		"product_id": 135,
		"product_name": "Street Fighter Set 2",
		"franchise_sort": 167,
		"img_name": "streetfighter2.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Street Fighter",
		"characters": "Cammy, Chun Li",
		"product_includes": "- Cammy\n- Chun Li",
		"has_accessory": ""
	},
	{
		"product_id": 136,
		"product_name": "Darkstalkers Set",
		"franchise_sort": 27,
		"img_name": "darkstalkers.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Darkstalkers",
		"characters": "Felicia, Morrigan",
		"product_includes": "- Felicia\n- Morrigan",
		"has_accessory": ""
	},
	{
		"product_id": 137,
		"product_name": "Joy and Jenny Set",
		"franchise_sort": 132,
		"img_name": "joyjenny.png",
		"big_character_count": 2,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 2.5,
		"price_adjust": "",
		"price": "$10",
		"total_character_count": 3,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Nurse Joy, Officer Jenny, Growlithe",
		"product_includes": "- Nurse Joy\n- Officer Jenny\n- Growlithe",
		"has_accessory": ""
	},
	{
		"product_id": 138,
		"product_name": "Pokémon Gen IV Player Set",
		"franchise_sort": 134,
		"img_name": "player_gen4.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Dawn, Lucas",
		"product_includes": "- Dawn\n- Lucas",
		"has_accessory": ""
	},
	{
		"product_id": 139,
		"product_name": "Pokémon Gen V Player Set",
		"franchise_sort": 135,
		"img_name": "player_gen5.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Hilbert, Hilda",
		"product_includes": "- Hilbert\n- Hilda",
		"has_accessory": ""
	},
	{
		"product_id": 140,
		"product_name": "Pokémon Gen V2 Player Set",
		"franchise_sort": 136,
		"img_name": "player_gen52.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Nate, Rosa",
		"product_includes": "- Nate\n- Rosa",
		"has_accessory": ""
	},
	{
		"product_id": 141,
		"product_name": "Crono",
		"franchise_sort": 24,
		"img_name": "crono.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Chrono Trigger",
		"characters": "Crono",
		"product_includes": "- Crono",
		"has_accessory": ""
	},
	{
		"product_id": 142,
		"product_name": "Chrono Trigger Set 1",
		"franchise_sort": 22,
		"img_name": "chronotrigger1.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Chrono Trigger",
		"characters": "Marle, Lucca, Robo",
		"product_includes": "- Marle\n- Lucca\n- Robo",
		"has_accessory": ""
	},
	{
		"product_id": 143,
		"product_name": "Chrono Trigger Set 2",
		"franchise_sort": 23,
		"img_name": "chronotrigger2.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Chrono Trigger",
		"characters": "Ayla, Frog, Magus",
		"product_includes": "- Ayla\n- Frog\n- Magus",
		"has_accessory": ""
	},
	{
		"product_id": 144,
		"product_name": "Slender Man",
		"franchise_sort": 172,
		"img_name": "slenderman.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 6,
		"category_name": "Miscellaneous",
		"franchise": "the internet",
		"characters": "Slender Man",
		"product_includes": "- Slender Man",
		"has_accessory": ""
	},
	{
		"product_id": 145,
		"product_name": "Jack Frost",
		"franchise_sort": 152,
		"img_name": "jackfrost.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "Rise of the Guardians",
		"characters": "Jack Frost",
		"product_includes": "- Jack Frost\n- staff accessory",
		"has_accessory": "TRUE"
	},
	{
		"product_id": 146,
		"product_name": "Deadpool",
		"franchise_sort": 94,
		"img_name": "deadpool.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 6,
		"category_name": "Miscellaneous",
		"franchise": "Marvel Comics",
		"characters": "Deadpool",
		"product_includes": "- Deadpool",
		"has_accessory": ""
	},
	{
		"product_id": 147,
		"product_name": "Birdy",
		"franchise_sort": 13,
		"img_name": "birdy.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Birdy: Decode",
		"characters": "Birdy",
		"product_includes": "- Birdy",
		"has_accessory": ""
	},
	{
		"product_id": 148,
		"product_name": "Cure Berry",
		"franchise_sort": 148,
		"img_name": "cureberry.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Pretty Cure",
		"characters": "Cure Berry",
		"product_includes": "- Cure Berry",
		"has_accessory": ""
	},
	{
		"product_id": 149,
		"product_name": "Motoko Kusanagi",
		"franchise_sort": 68,
		"img_name": "motoko_kusanagi.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Ghost in the Shell",
		"characters": "Motoko",
		"product_includes": "- Motoko",
		"has_accessory": ""
	},
	{
		"product_id": 150,
		"product_name": "Kureha",
		"franchise_sort": 158,
		"img_name": "kureha.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Shining Wind",
		"characters": "Kureha",
		"product_includes": "- Kureha",
		"has_accessory": ""
	},
	{
		"product_id": 151,
		"product_name": "Makoto",
		"franchise_sort": 15,
		"img_name": "makoto.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "BlazBlue",
		"characters": "Makoto",
		"product_includes": "- Makoto",
		"has_accessory": ""
	},
	{
		"product_id": 152,
		"product_name": "Dizzy",
		"franchise_sort": 69,
		"img_name": "dizzy.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Guilty Gear",
		"characters": "Dizzy",
		"product_includes": "- Dizzy",
		"has_accessory": ""
	},
	{
		"product_id": 153,
		"product_name": "Cities of Gold Set",
		"franchise_sort": 113,
		"img_name": "citiesofgold.png",
		"big_character_count": 3,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 3.5,
		"price_adjust": "",
		"price": "$14",
		"total_character_count": 4,
		"category_id": 5,
		"category_name": "Western Animation",
		"franchise": "Mysterious Cities of Gold",
		"characters": "Esteban, Zia, Tao, Kokapetl",
		"product_includes": "- Esteban\n- Zia\n- Tao\n- Kokapetl",
		"has_accessory": ""
	},
	{
		"product_id": 154,
		"product_name": "Firefly Set 1",
		"franchise_sort": 59,
		"img_name": "firefly1.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Firefly",
		"characters": "Mal, Inara, Book",
		"product_includes": "- Mal\n- Inara\n- Book",
		"has_accessory": ""
	},
	{
		"product_id": 155,
		"product_name": "Firefly Set 2",
		"franchise_sort": 60,
		"img_name": "firefly2.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Firefly",
		"characters": "Zoe, Wash, Jayne",
		"product_includes": "- Zoe\n- Wash\n- Jayne",
		"has_accessory": ""
	},
	{
		"product_id": 156,
		"product_name": "Firefly Set 3",
		"franchise_sort": 61,
		"img_name": "firefly3.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Firefly",
		"characters": "Kaylee, Simon, River",
		"product_includes": "- Kaylee\n- Simon\n- River",
		"has_accessory": ""
	},
	{
		"product_id": 157,
		"product_name": "Zevran",
		"franchise_sort": 48,
		"img_name": "zevran.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Dragon Age",
		"characters": "Zevran",
		"product_includes": "- Zevran",
		"has_accessory": ""
	},
	{
		"product_id": 158,
		"product_name": "Nariko",
		"franchise_sort": 73,
		"img_name": "nariko.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Heavenly Sword",
		"characters": "Nariko",
		"product_includes": "- Nariko",
		"has_accessory": ""
	},
	{
		"product_id": 159,
		"product_name": "Final Fantasy XIII Set",
		"franchise_sort": 58,
		"img_name": "ff13.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Final Fantasy (XIII)",
		"characters": "Lightning, Hope",
		"product_includes": "- Lightning\n- Hope",
		"has_accessory": ""
	},
	{
		"product_id": 160,
		"product_name": "DW New Companions Set 2",
		"franchise_sort": 46,
		"img_name": "dwnewcompanions2.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Doctor Who",
		"characters": "Amy, Rory, River",
		"product_includes": "- Amy\n- Rory\n- River",
		"has_accessory": ""
	},
	{
		"product_id": 161,
		"product_name": "Street Fighter Set 3",
		"franchise_sort": 168,
		"img_name": "streetfighter3.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Street Fighter",
		"characters": "Sakura, Juri",
		"product_includes": "- Sakura\n- Juri",
		"has_accessory": ""
	},
	{
		"product_id": 162,
		"product_name": "Kiki’s Delivery Service Set",
		"franchise_sort": 87,
		"img_name": "kiki.png",
		"big_character_count": 1,
		"mini_character_count": 1,
		"pts_adjust": "",
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Kiki’s Delivery Service",
		"characters": "Kiki, Jiji",
		"product_includes": "- Kiki\n- Jiji",
		"has_accessory": ""
	},
	{
		"product_id": 163,
		"product_name": "Rachel Alucard",
		"franchise_sort": 17,
		"img_name": "rachel_alucard.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "BlazBlue",
		"characters": "Rachel",
		"product_includes": "- Rachel",
		"has_accessory": ""
	},
	{
		"product_id": 164,
		"product_name": "Platinum the Trinity",
		"franchise_sort": 16,
		"img_name": "platinum.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "BlazBlue",
		"characters": "Platinum",
		"product_includes": "- Platinum\n- staff accessory",
		"has_accessory": "TRUE"
	},
	{
		"product_id": 165,
		"product_name": "Squid Girl",
		"franchise_sort": 163,
		"img_name": "squidgirl.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Squid Girl",
		"characters": "Squid Girl",
		"product_includes": "- Squid Girl",
		"has_accessory": ""
	},
	{
		"product_id": 166,
		"product_name": "Attack on Titan Set",
		"franchise_sort": 9,
		"img_name": "attackontitan.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Attack on Titan",
		"characters": "Eren, Mikasa, Armin",
		"product_includes": "- Eren\n- Mikasa\n- Armin",
		"has_accessory": ""
	},
	{
		"product_id": 167,
		"product_name": "Skuld",
		"franchise_sort": 2,
		"img_name": "skuld.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": 0.5,
		"total_pts": 1.5,
		"price_adjust": "",
		"price": "$6",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Ah! My Goddess",
		"characters": "Skuld",
		"product_includes": "- Skuld\n- mallet accessory",
		"has_accessory": "TRUE"
	},
	{
		"product_id": 168,
		"product_name": "Sylveon",
		"franchise_sort": 143,
		"img_name": "sylveon.png",
		"big_character_count": "",
		"mini_character_count": 1,
		"pts_adjust": 0.5,
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 4,
		"category_name": "Pokémon",
		"franchise": "Pokémon",
		"characters": "Sylveon",
		"product_includes": "- Sylveon",
		"has_accessory": ""
	},
	{
		"product_id": 169,
		"product_name": "Star Trek TOS Set",
		"franchise_sort": 164,
		"img_name": "startrek_tos.png",
		"big_character_count": 3,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 3,
		"price_adjust": "",
		"price": "$12",
		"total_character_count": 3,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Star Trek TOS",
		"characters": "Kirk, Spock, McCoy",
		"product_includes": "- Kirk\n- Spock\n- McCoy",
		"has_accessory": ""
	},
	{
		"product_id": 170,
		"product_name": "Tamaki",
		"franchise_sort": 125,
		"img_name": "tamaki.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Ouran Host Club",
		"characters": "Tamaki",
		"product_includes": "- Tamaki",
		"has_accessory": ""
	},
	{
		"product_id": 171,
		"product_name": "Twelfth Doctor",
		"franchise_sort": 43,
		"img_name": "doc12.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Doctor Who",
		"characters": "Twelfth Doctor",
		"product_includes": "- Twelfth Doctor",
		"has_accessory": ""
	},
	{
		"product_id": 172,
		"product_name": "Lewis",
		"franchise_sort": 114,
		"img_name": "lewis.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 6,
		"category_name": "Miscellaneous",
		"franchise": "Mystery Machine Ghost",
		"characters": "Lewis",
		"product_includes": "- Lewis",
		"has_accessory": ""
	},
	{
		"product_id": 173,
		"product_name": "One Punch Man",
		"franchise_sort": 120,
		"img_name": "onepunch.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "One Punch Man",
		"characters": "One Punch Man",
		"product_includes": "- One Punch Man",
		"has_accessory": ""
	},
	{
		"product_id": 174,
		"product_name": "Hunter x Hunter Set",
		"franchise_sort": 79,
		"img_name": "hxh.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Hunter x Hunter",
		"characters": "Gon, Killua",
		"product_includes": "- Gon\n- Killua",
		"has_accessory": ""
	},
	{
		"product_id": 175,
		"product_name": "Skeleton Brothers Set",
		"franchise_sort": 177,
		"img_name": "skeletonbros.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Undertale",
		"characters": "Papyrus, Sans",
		"product_includes": "- Papyrus\n- Sans",
		"has_accessory": ""
	},
	{
		"product_id": 176,
		"product_name": "Harry Potter",
		"franchise_sort": 71,
		"img_name": "harrypotter.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "$4",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Harry Potter",
		"characters": "Harry Potter",
		"product_includes": "- Harry Potter",
		"has_accessory": ""
	},
	{
		"product_id": 177,
		"product_name": "Escaflowne Girls Set",
		"franchise_sort": 53,
		"img_name": "escagirls.png",
		"big_character_count": 2,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 2,
		"price_adjust": "",
		"price": "$8",
		"total_character_count": 2,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Escaflowne",
		"characters": "Hitomi, Merle",
		"product_includes": "- Hitomi\n- Merle",
		"has_accessory": ""
	},
	{
		"product_id": 178,
		"product_name": "Angel/Kanade",
		"franchise_sort": 4,
		"img_name": "kanade_angel.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Angel Beats",
		"characters": "Angel/Kanade",
		"product_includes": "- Angel/Kanade",
		"has_accessory": ""
	},
	{
		"product_id": 179,
		"product_name": "Otonashi",
		"franchise_sort": 5,
		"img_name": "otonashi.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Angel Beats",
		"characters": "Otonashi",
		"product_includes": "- Otonashi",
		"has_accessory": ""
	},
	{
		"product_id": 180,
		"product_name": "Yuri",
		"franchise_sort": 6,
		"img_name": "yuri.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Angel Beats",
		"characters": "Yuri",
		"product_includes": "- Yuri",
		"has_accessory": ""
	},
	{
		"product_id": 181,
		"product_name": "Menma",
		"franchise_sort": 8,
		"img_name": "menma.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Anohana",
		"characters": "Menma",
		"product_includes": "- Menma",
		"has_accessory": ""
	},
	{
		"product_id": 182,
		"product_name": "Pazu",
		"franchise_sort": 20,
		"img_name": "pazu.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Castle in the Sky",
		"characters": "Pazu",
		"product_includes": "- Pazu",
		"has_accessory": ""
	},
	{
		"product_id": 183,
		"product_name": "Sheeta",
		"franchise_sort": 21,
		"img_name": "sheeta.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Castle in the Sky",
		"characters": "Sheeta",
		"product_includes": "- Sheeta",
		"has_accessory": ""
	},
	{
		"product_id": 184,
		"product_name": "Howl",
		"franchise_sort": 77,
		"img_name": "howl.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Howl's Moving Castle",
		"characters": "Howl",
		"product_includes": "- Howl",
		"has_accessory": ""
	},
	{
		"product_id": 185,
		"product_name": "Sophie",
		"franchise_sort": 78,
		"img_name": "sophie.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Howl's Moving Castle",
		"characters": "Sophie",
		"product_includes": "- Sophie",
		"has_accessory": ""
	},
	{
		"product_id": 186,
		"product_name": "Haruhi Fujioka",
		"franchise_sort": 121,
		"img_name": "haruhi_fujioka.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Ouran Host Club",
		"characters": "Haruhi Fujioka",
		"product_includes": "- Haruhi Fujioka",
		"has_accessory": ""
	},
	{
		"product_id": 187,
		"product_name": "Hikaru Hitachiin",
		"franchise_sort": 122,
		"img_name": "hikaru_hitachiin.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Ouran Host Club",
		"characters": "Hikaru Hitachiin",
		"product_includes": "- Hikaru Hitachiin",
		"has_accessory": ""
	},
	{
		"product_id": 188,
		"product_name": "Kaoru Hitachiin",
		"franchise_sort": 123,
		"img_name": "kaoru_hitachiin.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Ouran Host Club",
		"characters": "Kaoru Hitachiin",
		"product_includes": "- Kaoru Hitachiin",
		"has_accessory": ""
	},
	{
		"product_id": 189,
		"product_name": "Kyoya",
		"franchise_sort": 124,
		"img_name": "kyoya.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 1,
		"category_name": "Anime / Manga",
		"franchise": "Ouran Host Club",
		"characters": "Kyoya",
		"product_includes": "- Kyoya",
		"has_accessory": ""
	},
	{
		"product_id": 190,
		"product_name": "Nathan Drake",
		"franchise_sort": 176,
		"img_name": "nathandrake.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 2,
		"category_name": "Video Game",
		"franchise": "Uncharted",
		"characters": "Nathan Drake",
		"product_includes": "- Nathan Drake",
		"has_accessory": ""
	},
	{
		"product_id": 191,
		"product_name": "Indiana Jones",
		"franchise_sort": 80,
		"img_name": "indianajones.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Indiana Jones",
		"characters": "Indiana Jones",
		"product_includes": "- Indiana Jones",
		"has_accessory": ""
	},
	{
		"product_id": 192,
		"product_name": "Walter Mitty",
		"franchise_sort": 179,
		"img_name": "waltermitty.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Walter Mitty (2013)",
		"characters": "Walter Mitty",
		"product_includes": "- Walter Mitty",
		"has_accessory": ""
	},
	{
		"product_id": 193,
		"product_name": "Captain America",
		"franchise_sort": 93,
		"img_name": "captainamerica.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 6,
		"category_name": "Miscellaneous",
		"franchise": "Marvel Comics",
		"characters": "Captain America",
		"product_includes": "- Captain America",
		"has_accessory": ""
	},
	{
		"product_id": 194,
		"product_name": "Dr. Strange",
		"franchise_sort": 95,
		"img_name": "drstrange.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 6,
		"category_name": "Miscellaneous",
		"franchise": "Marvel Comics",
		"characters": "Dr. Strange",
		"product_includes": "- Dr. Strange",
		"has_accessory": ""
	},
	{
		"product_id": 195,
		"product_name": "Thirteenth Doctor",
		"franchise_sort": 44,
		"img_name": "doc13.png",
		"big_character_count": 1,
		"mini_character_count": "",
		"pts_adjust": "",
		"total_pts": 1,
		"price_adjust": "",
		"price": "",
		"total_character_count": 1,
		"category_id": 3,
		"category_name": "Live Action",
		"franchise": "Doctor Who",
		"characters": "Thirteenth Doctor",
		"product_includes": "- Thirteenth Doctor",
		"has_accessory": ""
	}
];
